config:
  # General configuration of the framework
  general:
    sample: 1
  # Datasets
  datasets:
    # Text dataset (MovieLenz 25M)
    text_dataset:
      # Dataset name
      name: movielens-25m
      # Path to the dataset
      url: https://files.grouplens.org/datasets/movielens/ml-25m.zip
    # Visual dataset (SceneSense)
    visual_dataset:
      # Dataset name
      name: SceneSense-visual
      # Path to the dataset
      path_metadata: https://huggingface.co/datasets/alitourani/moviefeats_visual/resolve/main/stats.json
      # Path to the features
      path_raw: https://huggingface.co/datasets/alitourani/moviefeats_visual/blob/main/
      # Feature sources to be used (in an array)
      # Possible values: ["full_movies", "movie_shots", "movie_trailers"]
      feature_sources: ["full_movies", "movie_shots", "movie_trailers"]
      # Feature extraction models to be used (in an array)
      # Possible values: ["incp3", "vgg19"]
      feature_models: ["incp3", "vgg19"]
  pipelines:
    # Movie trailers finder and downloader pipeline
    movie_trailers:
      # Pipeline name
      name: Trailer-fetcher
      # Path to the pipeline
      download_path: "~/Downloads"
  # Aggregations
  aggregations:
    # Pointwise aggregation
    pointwise:
      include: true
    # Distributional aggregation
    distributional:
      include: true
    # Temporal aggregation
    temporal:
      include: true
