config:
  # General configuration of the framework
  general:
    sample: 1
  # Datasets
  datasets:
    # Text dataset (MovieLenz 25M)
    text_dataset:
      # Dataset name
      name: movielens-25m
      # Path to the dataset
      url: https://files.grouplens.org/datasets/movielens/ml-25m.zip
    # Visual dataset (SceneSense)
    visual_dataset:
      # Dataset name
      name: SceneSense-visual
      # Path to the dataset
      path_metadata: https://huggingface.co/datasets/alitourani/moviefeats_visual/resolve/main/stats.json
      # Path to the features
      path_raw: https://huggingface.co/datasets/alitourani/moviefeats_visual/blob/main/
      # Feature sources to be used (in an array)
      # Possible values: ["full_movies", "movie_shots", "movie_trailers"]
      feature_sources: ["full_movies", "movie_shots", "movie_trailers"]
      # Feature extraction models to be used (in an array)
      # Possible values: ["incp3", "vgg19"]
      feature_models: ["incp3", "vgg19"]
  pipelines:
    # Movie trailers finder and downloader pipeline
    movie_trailers:
      # Pipeline name
      name: Trailer-fetcher
      # Path to the pipeline
      download_path: "~/Downloads"
    # Movie frames extractor pipeline
    movie_frames:
      # Pipeline name
      name: Frame-extractor
      # Movies path
      movies_path: "E:/Datasets/Movies/Videos"
      # Frames path
      frames_path: "E:/Datasets/Movies/MovieFrames"
      # Supported video formats
      video_formats: ["mp4", "avi", "mkv"]
      # Frequency of frames extraction (picking 'n' frames every second)
      frequency: 1
      # Output file format
      output_format: "jpg"
      # Feature extraction model input size (width)
      model_input_size: 420
    # Movie frames visual feature extractor pipeline
    movie_frames_visual_features:
      # Pipeline name
      name: Visual-feature-extractor
      # Path the root directory containing the frames in folders
      # [Note] it is equal to the frames_path in the movie_frames pipeline
      movies_frames_path: "E:/Datasets/Movies/MovieFrames"
      # Frames path
      features_path: "E:/Datasets/Movies/MovieFeatures"
      # Supported image (saved frames) formats
      image_formats: ["png", "jpg", "jpeg"]
  # Aggregations
  aggregations:
    # Pointwise aggregation
    pointwise:
      include: true
    # Distributional aggregation
    distributional:
      include: true
    # Temporal aggregation
    temporal:
      include: true
