config:
  # General configuration of the framework
  general:
    # Framework run mode
    mode: "pipeline" # Possible values: ["ds", "pipeline", "recsys"]
    # Framework sub-mode
    # Sub-mode of the dataset mode - Possible values: ["scenesense_meta", "scenesense_visual"]
    sub_mode_ds: "scenesense_meta"
    # Sub-mode of the pipeline mode
    # Possible values: ["dl_trailers", "frame_extractor", "feat_extractor", "shot_from_frames", "shot_from_feat"]
    sub_mode_pipeline: "shot_from_feat"
    # Sub-mode of the recommendation system mode - Possible values: ["pointwise", "distributional", "temporal"]
    sub_mode_recsys: "pointwise"
  # Datasets
  datasets:
    # Text dataset (MovieLenz 25M)
    text_dataset:
      # Dataset name
      name: movielens-25m
      # Path to the dataset
      url: https://files.grouplens.org/datasets/movielens/ml-25m.zip
    # Visual dataset (SceneSense)
    visual_dataset:
      # Dataset name
      name: SceneSense-visual
      # Path to the dataset
      path_metadata: https://huggingface.co/datasets/alitourani/moviefeats_visual/resolve/main/stats.json
      # Path to the features
      path_raw: https://huggingface.co/datasets/alitourani/moviefeats_visual/blob/main/
      # Feature sources to be used (in an array)
      # Possible values: ["full_movies", "movie_shots", "movie_trailers"]
      feature_sources: ["full_movies", "movie_shots", "movie_trailers"]
      # Feature extraction models to be used (in an array)
      # Possible values: ["incp3", "vgg19"]
      feature_models: ["incp3", "vgg19"]
  pipelines:
    # Movie trailers finder and downloader pipeline
    movie_trailers:
      # Pipeline name
      name: Trailer-fetcher
      # Path to the pipeline
      download_path: "~/Downloads"
    # Movie frames extractor pipeline
    movie_frames:
      # Pipeline name
      name: Frame-extractor
      # Movies path
      movies_path: "E:/Datasets/Movies/Videos"
      # Frames path
      frames_path: "E:/Datasets/Movies/MovieFrames"
      # Supported video formats
      video_formats: ["mp4", "avi", "mkv"]
      # Frequency of frames extraction (picking 'n' frames every second)
      frequency: 1
      # Output file format
      output_format: "jpg"
      # Feature extraction model input size (width)
      model_input_size: 420
    # Movie frames visual feature extractor pipeline
    movie_frames_visual_features:
      # Pipeline name
      name: Visual-feature-extractor
      # Path the root directory containing the frames in folders
      # [Note] it is equal to the frames_path in the movie_frames pipeline
      frames_path: "E:/Datasets/Movies/MovieFrames"
      # Features path
      features_path: "E:/Datasets/Movies/MovieFeatures"
      # Supported image (saved frames) formats
      image_formats: ["png", "jpg", "jpeg"]
      # Feature extraction models to be used (in an array)
      # Possible values: ["incp3", "vgg19"]
      feature_extractor_model: "incp3"
      # Packets size (number of frames in each packet)
      packet_size: 25
    # Movie frames and extracted features shot detection pipeline
    movie_shots:
      # Pipeline name
      name: Shot-detector
      # Variants of shot detection
      variants:
        # Shot detection from frames
        from_frames:
          # Input frames path
          frames_path: "E:/Datasets/Movies/MovieFrames"
          # Output shot frames path
          shot_frames_path: "E:/Datasets/Movies/MovieShotsFrames"
          # Supported input image (saved frames) formats
          image_formats: ["png", "jpg", "jpeg"]
          # Output file format
          output_format: "jpg"
        # Shot detection from features
        from_features:
          # Input features path
          features_path: "E:/Datasets/Movies/MovieFeatures"
          # Output shot features path
          shot_features_path: "E:/Datasets/Movies/MovieShotsFeatures"
          # Shot boundaries detection threshold
          threshold: 0.7
          # Packets size (number of frames in each packet)
          # [Note] it is recommended to set it equal to the packet_size in the movie_frames_visual_features pipeline
          packet_size: 25
  # Aggregations
  aggregations:
    # Pointwise aggregation
    pointwise:
      include: true
    # Distributional aggregation
    distributional:
      include: true
    # Temporal aggregation
    temporal:
      include: true
